name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build-go:
    name: Build Go implementation
    runs-on: ubuntu-latest
    steps:
      - name: Prepare metadata
        id: meta
        run: |
          echo "::set-output name=version::${GITHUB_REF##*/}"
          echo "::set-output name=version_short::${GITHUB_REF##*/v}"
      - name: Setup Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Check out project files
        uses: actions/checkout@v1
      - name: Build
        id: build
        run: |
          cd go
          export PATH=$PATH:$(go env GOPATH)/bin
          make PACKAGE=quorum-plugin-hello-world-go VERSION=${{ steps.meta.outputs.version_short }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: go-artifacts
          path: go/build
  build-java:
    name: Build Java implementation
    runs-on: ubuntu-latest
    steps:
      - name: Prepare metadata
        id: meta
        run: |
          echo "::set-output name=version::${GITHUB_REF##*/}"
          echo "::set-output name=version_short::${GITHUB_REF##*/v}"
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check out project files
        uses: actions/checkout@master
        with:
          submodules: recursive
      - name: Load cached dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build
        id: build
        run: |
          cd java
          mvn clean package -Dpackage=quorum-plugin-hello-world-java -Dversion=${{ steps.meta.outputs.version_short }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: java-artifacts
          path: java/target/dist
  prepare-deploy:
    name: Prepare package ${{ matrix.package }}
    needs:
      - build-go
      - build-java
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ["quorum-plugin-hello-world-go", "quorum-plugin-hello-world-java"]
    steps:
      - name: Setup jfrog CLI
        uses: jfrog/setup-jfrog-cli@v1
      - name: Prepare metadata
        id: meta
        run: |
          echo "::set-output name=version::${GITHUB_REF##*/}"
          echo "::set-output name=package::${{ matrix.package }}"
      - name: Prepare ${{ steps.meta.outputs.package }}@${{ steps.meta.outputs.version }} in Bintray
        run: |
          CHECK_PACKAGE="${{ secrets.BINTRAY_ORGANIZATION }}/${{ secrets.BINTRAY_REPOSITORY }}/${{ steps.meta.outputs.package }}"
          CHECK_VERSION="$CHECK_PACKAGE/${{ steps.meta.outputs.version }}"
          echo "Checking $CHECK_PACKAGE"
          jfrog bt package-show --key ${{ secrets.BINTRAY_API_KEY }} --user ${{ secrets.BINTRAY_USER }} $CHECK_PACKAGE
          echo "Checking $CHECK_VERSION"
          jfrog bt version-show --key ${{ secrets.BINTRAY_API_KEY }} --user ${{ secrets.BINTRAY_USER }} $CHECK_VERSION && x=0 || x=1
          if [ $x -eq 0 ]; then
            echo "$CHECK_VERSION already exists"
          else
            jfrog bt version-create --key ${{ secrets.BINTRAY_API_KEY }} --user ${{ secrets.BINTRAY_USER }} \
                  --vcs-tag ${{ steps.meta.outputs.version }} --released $(date -u +"%Y-%m-%dT%H:%M:%SZ") \
                  $CHECK_VERSION
          fi
  deploy:
    name: Deploy ${{ matrix.artifact }}/${{ matrix.arch }}/${{ matrix.extension }} to Bintray
    needs:
      - prepare-deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["linux-amd64", "darwin-amd64"]
        artifact: ["go-artifacts", "java-artifacts"]
    steps:
      - name: Setup jfrog CLI
        uses: jfrog/setup-jfrog-cli@v1
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: ${{ matrix.artifact }}
      - name: Prepare metadata
        id: meta
        run: |
          echo "::set-output name=package::$(cat ${{ matrix.artifact }}/plugin-meta.json | jq -r .name)"
          echo "::set-output name=version::${GITHUB_REF##*/}"
          echo "::set-output name=version_short::${GITHUB_REF##*/v}"
      - name: Upload to Bintray
        run: |
          jfrog bt upload --key ${{ secrets.BINTRAY_API_KEY }} --user ${{ secrets.BINTRAY_USER }} --publish --override \
                "${{ matrix.artifact }}/${{ matrix.arch }}/${{ steps.meta.outputs.package }}-${{ steps.meta.outputs.version_short }}.*" \
                ${{ secrets.BINTRAY_ORGANIZATION }}/${{ secrets.BINTRAY_REPOSITORY }}/${{ steps.meta.outputs.package }}/${{ steps.meta.outputs.version }} \
                ${{ steps.meta.outputs.package }}/${{ steps.meta.outputs.version }}/${{ matrix.arch }}/
  notify:
    name: Notify Slack
    needs:
      - build-go
      - build-java
      - prepare-deploy
      - deploy
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Slack message
        id: status
        uses: actions/github-script@0.8.0
        with:
          script: |
            ////////////////////////////////////
            // retrieve workflow run data
            ////////////////////////////////////

            console.log("get workflow run")
            const wf_run = await github.actions.getWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: ${{ github.run_id }}
            })
            console.log("get jobs for workflow run:", wf_run.data.jobs_url)
            const jobs_response = await github.request(wf_run.data.jobs_url)

            ////////////////////////////////////
            // build slack notification message
            ////////////////////////////////////

            // some utility functions
            var date_diff_func = function(start, end) {
                var duration = end - start
                // format the duration
                var delta = duration / 1000
                var days = Math.floor(delta / 86400)
                delta -= days * 86400
                var hours = Math.floor(delta / 3600) % 24
                delta -= hours * 3600
                var minutes = Math.floor(delta / 60) % 60
                delta -= minutes * 60
                var seconds = Math.floor(delta % 60)
                var format_func = function(v, text, check) {
                    if (v <= 0 && check) {
                        return ""
                    } else {
                        return v + text
                    }
                }
                return format_func(days, "d", true) + format_func(hours, "h", true) + format_func(minutes, "m", true) + format_func(seconds, "s", false)
            }
            var status_icon_func = function(s) {
                switch (s) {
                case "success":
                    return ":white_check_mark:"
                case "failure":
                    return ":no_entry:"
                default:
                    return ":z:"
                }
            }
            const commit = "${{ github.sha }}".substr(0, 6)

            // build the message
            var fields = []
            var workflow_status = "success"
            for (j of jobs_response.data.jobs) {
                console.log(j.name, ":", j.status, j.conclusion, j.started_at, j.completed_at)
                // ignore the current job running this script
                if (j.status != "completed") {
                    continue
                }
                if (j.conclusion == "failure") {
                    workflow_status = "failure"
                }
                fields.push({
                    type: "mrkdwn",
                    text: status_icon_func(j.conclusion) + " <" + j.html_url + "|*" + j.name + "*>\n   \u21b3 completed in " + date_diff_func(new Date(j.started_at), new Date(j.completed_at))
                })
            }

            var slack_msg = {
                blocks: [
                    {
                        type: "section",
                        text: {
                            type: "mrkdwn",
                            text: "<https://github.com/${{ github.repository }}|*${{ github.repository }}*>\nfrom *${{ github.ref }}@" + commit + "*"
                        }
                    },
                    {
                        type: "section",
                        text: {
                            type: "mrkdwn",
                            text: status_icon_func(workflow_status) + " *${{ github.workflow }}*\nWorkflow run <" + wf_run.data.html_url + "|#${{ github.run_number }}> completed in " + date_diff_func(new Date(wf_run.data.created_at), new Date(wf_run.data.updated_at))
                        }
                    },
                    {
                        type: "divider"
                    },
                    {
                        type: "section",
                        fields: fields
                    }
                ]
            }
            return slack_msg
      - name: Send to Slack
        if: success()
        run: |
          curl -X POST ${{ secrets.SLACK_WEBHOOK_URL}} -H "Content-type: application/json" --data '${{ steps.status.outputs.result }}'